### ISSUE TITLE
Uploads to multiple buckets from one grunt script

### ISSUE THREAD

**Issue by JamesHagerman** [jpillora/grunt-aws#15]
I've got an app that I need to put into two separate S3 buckets with slightly different files going to each. Grunt says "No files matched" using a config that looks like this:

https://gist.github.com/JamesHagerman/7aff419e11fb4b519afa

Any ideas on getting this to work?

**Comment by jpillora** [comment]
Just looked at this again, I think it should be:
``` js
  brand1: {
    options: {
      bucket: "brand1-bucket"
    },
    cwd: "build2/",
    src: "**"
  },
```
The `build: {...}` was causing it have no `src` set

**Comment by JamesHagerman** [comment]
I finally got it working with this help. Sorry about the delay!

Thank you!
