### ISSUE TITLE
Add an exclude option

### ISSUE THREAD

**Issue by evanplaice** [jpillora/grunt-aws#25]
Would it be possible to add an exclude option to the S3 sync tasks?

A simple array of files/folders to exclude would work.

**Comment by jpillora** [comment]
You should already be able to exclude files with glob options. Read more here http://gruntjs.com/configuring-tasks. It should look something like:

``` js
s3: {
  options: {
    accessKeyId: "<%= aws.accessKeyId %>",
    secretAccessKey: "<%= aws.secretAccessKey %>",
    bucket: "my-bucket"
  },

  //upload the img/ folder and all it's files EXCLUDING the secrets directory
  images: {
    src: [
      "img/**",
      "!img/secrets/**"
    ]
  }
}
```

**Untested**

**Comment by evanplaice** [comment]
Thanks. I didn't see that option in the documentation.
