### ISSUE TITLE
With the S3 task, charset adds to every mime-type

### ISSUE THREAD

**Issue by nephiw** [jpillora/grunt-aws#31]
I am adding dozens of files to different S3 buckets depending upon if I am releasing to staging, production, or beta. So I already have the 6 different S3 tasks (each one has 2 cache control configurations), but now I need to set the charset on html, css, and map files so they render properly in the browser.

Upon reading through the code, I see that the charset is added here: https://github.com/jpillora/grunt-aws/blob/master/tasks/services/s3.js#L325 and that the mime type is not consulted to determine if they should be added so I get Content-Types like this: `image/gif; charset=utf-8` which is not ideal.

I take this to mean that I need to add more tasks to separate the configuration of utf-8 encoded files separately of my image files. Is there a better way of handling this? Can I define the mime type to include charset for example?

**Comment by jpillora** [comment]
Closed by your PR https://github.com/jpillora/grunt-aws/pull/32 :)
