### ISSUE TITLE
Does not support authentication for buckets in newer regions

### ISSUE THREAD

**Issue by phw** [jpillora/grunt-aws#33]
I have setup a bucket in the new Frankfurt location. If I try to upload to it using grunt-aws I get the following error message:

> InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

According to http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4 newer regions will only support AWS4-HMAC-SHA256 and older authentication methods are deprecated.

I guess this can be fixed by upgrading to the latest version of aws-sdk.

**Comment by ragulka** [comment]
Having the same issue here

**Comment by jpillora** [comment]
Happy to give someone commit access to fix this issue
