### ISSUE TITLE
GZip encoding is breaking video media

### ISSUE THREAD

**Issue by listenrightmeow** [jpillora/grunt-aws#51]
When looping over video uploaded to S3 with this grunt task, the default GZip behavior uploads the content with the appropriate Content-Type header to gzip.

Problem is when playing back video or attempting to loop that video content, I'm met with 'net::ERR_CONTENT_DECODING_FAILED' as a response. This happens when viewing content directly from the S3 url or via Cloudfront.

**Comment by jpillora** [comment]
you can set `compress` to `false`
