### ISSUE TITLE
lodash@<3.0.0 is no longer maintained

### ISSUE THREAD

**Issue by luckydev** [jpillora/grunt-aws#59]
Pls upgrade the dependency in package.json to lodash@^4.0.0

**Comment by stuntbox** [comment]
Adding an explicit +1 to this. There is also a vulnerability with mime < v2 that should be addressed: https://nodesecurity.io/advisories/535

**Comment by redeleon** [comment]
+1 to this as well
lodash and mime

**Comment by stuntbox** [comment]
@jpillora Just saw you closed the issue. Any resolution?

**Comment by jpillora** [comment]
Bumped lodash in 0.7.0 though needs testing
